//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceDetection.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserImages = new HashSet<UserImage>();
        }
    
        public int UserID { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<UserImage> UserImages { get; set; }
    }
}
